using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Blazing.Mediator.SourceGenerators.Analyzers;
using Blazing.Mediator.SourceGenerators.Emitters;
using Blazing.Mediator.SourceGenerators.Models;

namespace Blazing.Mediator.SourceGenerators.Generators;

/// <summary>
/// The single consolidated incremental source generator for Blazing.Mediator.
/// Replaces all seven retired generators with one discovery → analysis → emit pipeline.
/// <para>
/// Pipeline:
/// <code>
///   ClassDeclarationSyntax (filtered)
///       ↓ Collect()
///   CompilationAnalyzer.Analyze(classes, rootNamespace)
///       ↓
///   CompilationModel
///       ↓
///   MediatorCodeWriter.Write(model)
///       ↓
///   "Mediator.g.cs"
/// </code>
/// </para>
/// </summary>
[Generator]
public sealed class IncrementalMediatorGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ── Step 1: Collect all class declarations that could be handlers or middleware.
        //    We use a broad filter (any class with a base list) to keep the predicate cheap.
        //    The heavy semantic analysis happens only in the transform step.
        var classSyntax = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _)  => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        // ── Step 2: Combine with the compilation so the analyzer has full semantic information.
        var combined = context.CompilationProvider.Combine(classSyntax);

        // ── Step 3: Register the source output.
        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (compilation, classes) = pair;
            Execute(compilation, classes, spc);
        });
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Predicate — cheap, run on every syntax node
    // ─────────────────────────────────────────────────────────────────────────

    private static bool IsCandidateClass(SyntaxNode node)
    {
        // Only consider non-abstract, non-generic classes that declare base types.
        // Abstract classes cannot be DI-resolved; open-generic handlers are unsupported.
        if (node is not ClassDeclarationSyntax classDecl)
            return false;

        return classDecl.BaseList is { Types.Count: > 0 };
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Execute — runs when the compilation or collected nodes change
    // ─────────────────────────────────────────────────────────────────────────

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        // NOTE: Do NOT early-return when classes is empty.
        // Projects such as multi-project AnalyzerExample have no local handler classes
        // (only top-level Program.cs statements), but still need the full ContainerMetadata
        // generated by DiscoverFromReferencedAssemblies in CompilationAnalyzer.Analyze().

        // Derive the root namespace from the assembly name as a best-effort fallback.
        // Consuming projects can override via <RootNamespace> in their .csproj.
        string rootNamespace = compilation.AssemblyName ?? "Generated";

        var analyzer = new CompilationAnalyzer(compilation);

        CompilationModel model;
        try
        {
            model = analyzer.Analyze(classes, rootNamespace);
        }
        catch (System.Exception ex)
        {
            // Surface analyzer exceptions as a diagnostic rather than crashing the generator host.
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "BM9000",
                    title: "Blazing.Mediator source generator failed",
                    messageFormat: "CompilationAnalyzer threw an unexpected exception: {0}",
                    category: "Blazing.Mediator.SourceGenerators",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                Location.None,
                ex.Message));
            return;
        }

        // Always generate output when the source generator is attached to a project.
        // Subscriber-only projects (no IRequestHandler/INotificationHandler) still need
        // the generated IMediator registration (ContainerMetadata, AddMediator, etc.).

        string source;
        try
        {
            bool allowUnsafe = compilation.Options is CSharpCompilationOptions csharpOptions && csharpOptions.AllowUnsafe;
            source = MediatorCodeWriter.Write(model, allowUnsafe);
        }
        catch (System.Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "BM9001",
                    title: "Blazing.Mediator source generator failed",
                    messageFormat: "MediatorCodeWriter threw an unexpected exception: {0}",
                    category: "Blazing.Mediator.SourceGenerators",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                Location.None,
                ex.Message));
            return;
        }

        context.AddSource("Mediator.g.cs", source);
    }
}
