//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for Blazing.Mediator.SourceGenerators.
//     
//     This is a compile-time model used during source generation.
//     It does not have access to runtime types from Blazing.Mediator.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Blazing.Mediator.SourceGenerators.Models;

/// <summary>
/// Compile-time model representing mediator configuration.
/// This is used during source generation to capture configuration settings
/// analyzed from AddMediator() calls or MSBuild properties.
/// </summary>
/// <remarks>
/// This class is used by the source generator at compile-time and does not reference
/// runtime types. The generated code will create a runtime version that wraps
/// the actual MediatorConfiguration instance.
/// </remarks>
internal sealed class GeneratedMediatorContextModel
{
    /// <summary>
    /// Initializes a new instance with default configuration values.
    /// </summary>
    public GeneratedMediatorContextModel()
    {
    }

    #region Telemetry Options (Runtime Toggleable)

    /// <summary>
    /// Gets or sets whether OpenTelemetry tracking is enabled.
    /// </summary>
    public bool IsTelemetryEnabled { get; set; }

    /// <summary>
    /// Gets or sets whether to capture detailed handler information in telemetry.
    /// </summary>
    public bool CaptureHandlerDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to capture detailed middleware information in telemetry.
    /// </summary>
    public bool CaptureMiddlewareDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to capture exception details in telemetry.
    /// </summary>
    public bool CaptureExceptionDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to capture notification handler details in telemetry.
    /// </summary>
    public bool CaptureNotificationHandlerDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to capture notification middleware details in telemetry.
    /// </summary>
    public bool CaptureNotificationMiddlewareDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to create child spans for individual handlers.
    /// </summary>
    public bool CreateHandlerChildSpans { get; set; }

    /// <summary>
    /// Gets or sets whether to capture subscriber metrics in telemetry.
    /// </summary>
    public bool CaptureSubscriberMetrics { get; set; }

    /// <summary>
    /// Gets or sets whether packet-level telemetry is enabled for streaming requests.
    /// </summary>
    public bool PacketLevelTelemetryEnabled { get; set; }

    /// <summary>
    /// Gets or sets whether streaming metrics are enabled.
    /// </summary>
    public bool EnableStreamingMetrics { get; set; }

    #endregion

    #region Statistics Options (Runtime Toggleable)

    /// <summary>
    /// Gets or sets whether statistics tracking is enabled.
    /// </summary>
    public bool IsStatisticsEnabled { get; set; }

    /// <summary>
    /// Gets or sets whether to track request (query/command) metrics.
    /// </summary>
    public bool EnableRequestMetrics { get; set; }

    /// <summary>
    /// Gets or sets whether to track notification metrics.
    /// </summary>
    public bool EnableNotificationMetrics { get; set; }

    /// <summary>
    /// Gets or sets whether to track middleware execution metrics.
    /// </summary>
    public bool EnableMiddlewareMetrics { get; set; }

    /// <summary>
    /// Gets or sets whether to enable performance counters.
    /// </summary>
    public bool EnablePerformanceCounters { get; set; }

    /// <summary>
    /// Gets or sets whether to enable detailed analysis features.
    /// </summary>
    public bool EnableDetailedAnalysis { get; set; }

    #endregion

    #region Logging Options (Runtime Toggleable)

    /// <summary>
    /// Gets or sets whether logging is enabled at all.
    /// </summary>
    public bool IsLoggingEnabled { get; set; }

    /// <summary>
    /// Gets or sets whether to log Send operations.
    /// </summary>
    public bool EnableSend { get; set; }

    /// <summary>
    /// Gets or sets whether to log Publish operations.
    /// </summary>
    public bool EnablePublish { get; set; }

    /// <summary>
    /// Gets or sets whether to log SendStream operations.
    /// </summary>
    public bool EnableSendStream { get; set; }

    /// <summary>
    /// Gets or sets whether to log request middleware execution.
    /// </summary>
    public bool EnableRequestMiddleware { get; set; }

    /// <summary>
    /// Gets or sets whether to log notification middleware execution.
    /// </summary>
    public bool EnableNotificationMiddleware { get; set; }

    /// <summary>
    /// Gets or sets whether to log detailed handler information.
    /// </summary>
    public bool EnableDetailedHandlerInfo { get; set; }

    /// <summary>
    /// Gets or sets whether to log middleware execution order.
    /// </summary>
    public bool EnableMiddlewareExecutionOrder { get; set; }

    /// <summary>
    /// Gets or sets whether to log performance timing information.
    /// </summary>
    public bool EnablePerformanceTiming { get; set; }

    /// <summary>
    /// Gets or sets whether to log subscriber details for notifications.
    /// </summary>
    public bool EnableSubscriberDetails { get; set; }

    /// <summary>
    /// Gets or sets whether to log middleware constraint validation.
    /// </summary>
    public bool EnableConstraintLogging { get; set; }

    #endregion

    #region Discovery Options (Build-Time Frozen)

    /// <summary>
    /// Gets or sets whether middleware discovery is enabled.
    /// NOTE: This value is frozen at build time in generated code.
    /// </summary>
    public bool DiscoverMiddleware { get; set; } = true;

    /// <summary>
    /// Gets or sets whether notification middleware discovery is enabled.
    /// NOTE: This value is frozen at build time in generated code.
    /// </summary>
    public bool DiscoverNotificationMiddleware { get; set; } = true;

    /// <summary>
    /// Gets or sets whether constrained middleware discovery is enabled.
    /// NOTE: This value is frozen at build time in generated code.
    /// </summary>
    public bool DiscoverConstrainedMiddleware { get; set; } = true;

    /// <summary>
    /// Gets or sets whether notification handler discovery is enabled.
    /// NOTE: This value is frozen at build time in generated code.
    /// </summary>
    public bool DiscoverNotificationHandlers { get; set; } = true;

    #endregion

    /// <summary>
    /// Creates a default configuration model with all discovery enabled
    /// and optional features disabled.
    /// </summary>
    public static GeneratedMediatorContextModel CreateDefault()
    {
        return new GeneratedMediatorContextModel
        {
            // Discovery enabled by default
            DiscoverMiddleware = true,
            DiscoverNotificationMiddleware = true,
            DiscoverConstrainedMiddleware = true,
            DiscoverNotificationHandlers = true,
            
            // Optional features disabled by default
            IsTelemetryEnabled = false,
            IsStatisticsEnabled = false,
            IsLoggingEnabled = false
        };
    }
}
