using System.Runtime.CompilerServices;

namespace Blazing.Mediator.SourceGenerators.Tests;

/// <summary>
/// Module initializer for test setup.
/// Configures Verify settings for consistent snapshot testing.
/// </summary>
public static class ModuleInitializer
{
    [ModuleInitializer]
    public static void Initialize()
    {
        // Disable framework-specific file names since generated code is the same across frameworks
        VerifierSettings.DontScrubProjectDirectory();
        
        // Use custom path derivation to avoid framework-specific suffixes
        DerivePathInfo((sourceFile, projectDirectory, type, method) =>
            new(directory: Path.GetDirectoryName(sourceFile)!));
        
        // Configure general Verify settings
        VerifierSettings.DontScrubDateTimes();
        VerifierSettings.DontScrubGuids();
        
        // Ignore volatile generated code elements
        VerifierSettings.ScrubLinesContaining(StringComparison.Ordinal,
            "// <auto-generated>",
            "// </auto-generated>",
            "This code was generated",
            "Changes to this file may cause incorrect behavior");
    }
}
