using System.Collections.Generic;
using System.Linq;
using System.Text;
using Blazing.Mediator.SourceGenerators.Analyzers;
using Blazing.Mediator.SourceGenerators.Models;

namespace Blazing.Mediator.SourceGenerators.Emitters;

/// <summary>
/// Emits the complete <c>Mediator.g.cs</c> output from a <see cref="CompilationModel"/>.
/// Replaces all seven retired generators with a single, cohesive output file.
/// Phase 1: Emits <c>RequestDispatcher</c>, <c>NotificationDispatcher</c>, <c>TelemetryTags</c>,
/// and per-type handler wrapper classes within the <c>Blazing.Mediator.Generated</c> namespace,
/// matching the contracts already expected by <c>Mediator.Send.cs</c> and <c>Mediator.Notification.cs</c>.
/// </summary>
internal static class MediatorCodeWriter
{
    // ─────────────────────────────────────────────────────────────────────────
    // Public entry point
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Generates the complete <c>Mediator.g.cs</c> source text.
    /// </summary>
    public static string Write(CompilationModel model, bool allowUnsafe = false)
    {
        var sb = new StringBuilder(16_384);

        AppendFileHeader(sb, allowUnsafe);

        // Everything lives in one namespace block.
        sb.AppendLine("""
            namespace Blazing.Mediator.Generated
            {
                using Microsoft.Extensions.DependencyInjection; // GetRequiredService, AddTransient etc.
            """);

        // ── Per-type handler wrapper classes ─────────────────────────────────
        foreach (var req in model.Requests)
        {
            AppendRequestWrapper(sb, req);
            sb.AppendLine();
        }

        foreach (var notif in model.Notifications)
        {
            AppendNotificationWrapper(sb, notif);
            sb.AppendLine();
        }

        // ── Container probe marker types ──────────────────────────────────────
        AppendContainerProbes(sb);
        sb.AppendLine();

        // ── ThrowHelper — [DoesNotReturn] methods for all dispatch error paths ───
        AppendThrowHelper(sb);
        sb.AppendLine();

        // ── ContainerMetadata ─────────────────────────────────────────────────
        AppendContainerMetadata(sb, model);
        sb.AppendLine();

        // ── RequestDispatcher ────────────────────────────────────────────────
        AppendRequestDispatcher(sb, model);
        sb.AppendLine();

        // ── NotificationDispatcher ───────────────────────────────────────────
        AppendNotificationDispatcher(sb, model);
        sb.AppendLine();

        // ── TelemetryTags + NotificationMetadata ─────────────────────────────
        AppendTelemetryTags(sb, model);
        sb.AppendLine();

        // ── MediatorTypeCatalog (AOT-clean compile-time handler catalog) ─────
        AppendTypeCatalog(sb, model);
        sb.AppendLine();

        sb.AppendLine("} // namespace Blazing.Mediator.Generated");

        // ── Service registration extension ───────────────────────────────────
        // Emitted in the Blazing.Mediator namespace (not .Generated) so that
        // services.AddMediator() resolves with just `using Blazing.Mediator;`
        // — identical to the hand-written extension it replaces.
        sb.AppendLine();
        sb.AppendLine("""
            namespace Blazing.Mediator
            {
                using Microsoft.Extensions.DependencyInjection; // AddSingleton, AddTransient etc.
                using Microsoft.Extensions.DependencyInjection.Extensions; // TryAddSingleton etc.
            """);
        AppendServiceRegistrationExtension(sb, model);
        sb.AppendLine("} // namespace Blazing.Mediator");

        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // File header
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendFileHeader(StringBuilder sb, bool allowUnsafe)
    {
        // [module: SkipLocalsInit] does not require the /unsafe compiler switch per se,
        // but some projects (e.g., AotTests, BenchmarkTemp) do not set AllowUnsafeBlocks.
        // Only emit when the consuming project already compiles with /unsafe (allowUnsafe=true).
        sb.AppendLine("""
            // <auto-generated/>
            // Generated by Blazing.Mediator.SourceGenerators — do not edit manually.
            // ReSharper disable All
            #nullable enable
            #pragma warning disable CS0436 // Type in source file conflicts with imported type
            #pragma warning disable CS9193 // Argument should be a variable (ref readonly Unsafe.AsRef pattern)
            #pragma warning disable CS8619 // Nullability of reference types in value doesn't match target type
            #pragma warning disable CS8631 // Nullability of type argument doesn't match constraint type
            #pragma warning disable CS8510 // The pattern is unreachable (duplicate switch arm due to cross-assembly discovery)
            """);

        if (allowUnsafe)
        {
            sb.AppendLine("""
                using global::System.Runtime.CompilerServices;
                [module: global::System.Runtime.CompilerServices.SkipLocalsInit]
                """);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Request handler wrappers
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendRequestWrapper(StringBuilder sb, RequestHandlerModel req)
    {
        // Ambiguous requests (multiple handlers) do not get a wrapper class.
        // The dispatcher emits a ThrowHelper.ThrowMultipleHandlers*() call instead.
        if (req.IsAmbiguous)
            return;

        string displayRequestType = XmlDocTypeName(req.RequestType);
        string summary = req.IsStream
            ? $"Generated per-scope dispatch wrapper for stream request <c>{displayRequestType}</c>."
            : req.IsVoid
                ? $"Generated per-scope dispatch wrapper for void command <c>{displayRequestType}</c>."
                : $"Generated per-scope dispatch wrapper for <c>{displayRequestType}</c>.";

        sb.AppendLine($$$"""
                /// <summary>{{{summary}}}</summary>
                /// <remarks>Wrappers are <c>sealed</c> instances held by <see cref="ContainerMetadata"/>.
                /// <c>Init(sp)</c> is called once per DI scope, pre-resolving handler and middleware from
                /// the scope's <see cref="global::System.IServiceProvider"/>. Subsequent <c>Handle()</c> calls
                /// within the same scope involve zero DI lookups.</remarks>
            """);
        sb.AppendLine("""
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            """);
        // Sealed instance class — holds pre-resolved handler + middleware references
        sb.AppendLine($$$"""
                internal sealed class RequestHandlerWrapper_{{{req.SafeName}}}
                {
            """);

        // Private fields: handler + one per middleware layer
        AppendHandlerWrapperFields(sb, req);
        sb.AppendLine();

        // Init() — called once by ContainerMetadata constructor with the root IServiceProvider
        AppendWrapperInitMethod(sb, req);
        sb.AppendLine();

        // Handle() — called per request; zero DI lookups when no middleware; minimal overhead with middleware
        if (req.IsStream)
            AppendStreamHandleMethod(sb, req);
        else if (req.IsVoid)
            AppendVoidHandleMethod(sb, req);
        else
            AppendResponseHandleMethod(sb, req);

        sb.AppendLine("    }");
    }

    // ── Handler + middleware field declarations ───────────────────────────────

    /// <summary>Emits private instance fields for the pre-resolved handler and middleware instances.</summary>
    private static void AppendHandlerWrapperFields(StringBuilder sb, RequestHandlerModel req)
    {
        sb.AppendLine($"        private {req.HandlerType} _handler = null!;");
        for (int i = 0; i < req.ApplicableMiddleware.Count; i++)
            sb.AppendLine($"        private {GetDiTypeName(req.ApplicableMiddleware[i])} _mw{i} = null!;");
        // Optional telemetry and statistics middleware — soft-resolved so the field is null when not configured.
        if (!req.IsVoid && !req.IsStream)
        {
            sb.AppendLine($$$"""
                    private global::Blazing.Mediator.Middleware.TelemetryMiddleware<{{{req.RequestType}}}, {{{req.ResponseType}}}>? _telMw;
                    private global::Blazing.Mediator.Middleware.StatisticsMiddleware<{{{req.RequestType}}}, {{{req.ResponseType}}}>? _statsMw;
                """);
        }
        if (req.IsVoid)
        {
            sb.AppendLine($$$"""
                    private global::Blazing.Mediator.Middleware.TelemetryMiddleware<{{{req.RequestType}}}>? _telMw;
                    private global::Blazing.Mediator.Middleware.StatisticsMiddleware<{{{req.RequestType}}}>? _statsMw;
                """);
        }
    }

    // ── Init method ───────────────────────────────────────────────────────────

    /// <summary>Emits the <c>Init(sp)</c> method that resolves handler and middleware from the root SP once.</summary>
    private static void AppendWrapperInitMethod(StringBuilder sb, RequestHandlerModel req)
    {
        sb.AppendLine("""
                    /// <summary>Resolves handler and all middleware instances from <paramref name="sp"/> once.
                    /// Called by <see cref="ContainerMetadata"/> once per DI scope with the scope's IServiceProvider.</summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            """);
        sb.AppendLine($$$"""
                public RequestHandlerWrapper_{{{req.SafeName}}} Init(global::System.IServiceProvider sp)
                {
            """);
        sb.AppendLine($"            _handler = sp.GetRequiredService<{req.HandlerType}>();");
        for (int i = 0; i < req.ApplicableMiddleware.Count; i++)
            sb.AppendLine($"            _mw{i} = sp.GetRequiredService<{GetDiTypeName(req.ApplicableMiddleware[i])}>();");
        // Soft-resolve telemetry and statistics middleware — returns null when not configured.
        if (!req.IsVoid && !req.IsStream)
        {
            sb.AppendLine($$$"""
                            _telMw = sp.GetService<global::Blazing.Mediator.Middleware.TelemetryMiddleware<{{{req.RequestType}}}, {{{req.ResponseType}}}>>();
                            _statsMw = sp.GetService<global::Blazing.Mediator.Middleware.StatisticsMiddleware<{{{req.RequestType}}}, {{{req.ResponseType}}}>>();
                """);
        }
        if (req.IsVoid)
        {
            sb.AppendLine($$$"""
                            _telMw = sp.GetService<global::Blazing.Mediator.Middleware.TelemetryMiddleware<{{{req.RequestType}}}>>();
                            _statsMw = sp.GetService<global::Blazing.Mediator.Middleware.StatisticsMiddleware<{{{req.RequestType}}}>>();
                """);
        }
        sb.AppendLine("""
                        return this;
                    }
            """);
    }

    // ── Response (query/command-with-response) ────────────────────────────────

    private static void AppendResponseHandleMethod(StringBuilder sb, RequestHandlerModel req)
    {
        sb.AppendLine($$$"""
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::System.Threading.Tasks.ValueTask<{{{req.ResponseType}}}> Handle(
                        {{{req.RequestType}}} request,
                        global::System.Threading.CancellationToken ct)
                    {
            """);

        if (req.ApplicableMiddleware.Count == 0)
        {
            // Zero-allocation fast path: [AggressiveInlining] + [NoInlining] slow-path split.
            // Without the split the JIT pre-allocates the delegate closures in the slow branch
            // even when _statsMw is null, causing 48 B of heap allocation per call.
            // By moving the slow path to HandleWithStats() (which carries [NoInlining]),
            // the closures are only emitted inside that method's frame and are never hoisted
            // into the fast-path's stack frame.
            sb.AppendLine("""
                            if (_statsMw is null && _telMw is null)
                                return _handler.Handle(request, ct);
                            return HandleWithStats(request, ct);
                        }

                """);
            // ── HandleWithStats — telemetry + statistics middleware pipeline ─
            // [NoInlining] ensures the lambda closures live only in this method's frame;
            // the aggressively-inlined Handle() fast path stays allocation-free.
            sb.AppendLine($$$"""
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
                        private global::System.Threading.Tasks.ValueTask<{{{req.ResponseType}}}> HandleWithStats(
                            {{{req.RequestType}}} request,
                            global::System.Threading.CancellationToken ct)
                        {
                            global::Blazing.Mediator.RequestHandlerDelegate<{{{req.ResponseType}}}> next = () => _handler.Handle(request, ct);
                            if (_telMw != null) { var prevTel0 = next; next = () => _telMw.HandleAsync(request, prevTel0, ct); }
                            if (_statsMw != null) { var prevStats0 = next; next = () => _statsMw.HandleAsync(request, prevStats0, ct); }
                            return next();
                """);
        }
        else
        {
            sb.AppendLine($"            global::Blazing.Mediator.RequestHandlerDelegate<{req.ResponseType}> next = () => _handler.Handle(request, ct);");
            AppendInstanceRequestMiddlewareChain(sb, req.ApplicableMiddleware);
            sb.AppendLine("""
                            if (_telMw != null) { var prevTel0 = next; next = () => _telMw.HandleAsync(request, prevTel0, ct); }
                            if (_statsMw != null) { var prevStats0 = next; next = () => _statsMw.HandleAsync(request, prevStats0, ct); }
                            return next();
                """);
        }

        sb.AppendLine("        }");
    }

    // ── Void command ──────────────────────────────────────────────────────────

    private static void AppendVoidHandleMethod(StringBuilder sb, RequestHandlerModel req)
    {
        sb.AppendLine($$$"""
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::System.Threading.Tasks.ValueTask Handle(
                        {{{req.RequestType}}} request,
                        global::System.Threading.CancellationToken ct)
                    {
            """);

        if (req.ApplicableMiddleware.Count == 0)
        {
            // Same fast-path / slow-path split as AppendResponseHandleMethod.
            // Prevents JIT-hoisted closure pre-allocation in the [AggressiveInlining] fast path.
            sb.AppendLine($$$"""
                            if (_statsMw is null && _telMw is null)
                                return _handler.Handle(request, ct);
                            return HandleWithStats(request, ct);
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
                        private global::System.Threading.Tasks.ValueTask HandleWithStats(
                            {{{req.RequestType}}} request,
                            global::System.Threading.CancellationToken ct)
                        {
                            global::Blazing.Mediator.RequestHandlerDelegate next = () => _handler.Handle(request, ct);
                            if (_telMw != null) { var prevTel0 = next; next = () => _telMw.HandleAsync(request, prevTel0, ct); }
                            if (_statsMw != null) { var prevStats0 = next; next = () => _statsMw.HandleAsync(request, prevStats0, ct); }
                            return next();
                """);
        }
        else
        {
            sb.AppendLine("            global::Blazing.Mediator.RequestHandlerDelegate next = () => _handler.Handle(request, ct);");
            AppendInstanceVoidMiddlewareChain(sb, req.ApplicableMiddleware);
            sb.AppendLine("""
                            if (_telMw != null) { var prevTel0 = next; next = () => _telMw.HandleAsync(request, prevTel0, ct); }
                            if (_statsMw != null) { var prevStats0 = next; next = () => _statsMw.HandleAsync(request, prevStats0, ct); }
                            return next();
                """);
        }

        sb.AppendLine("        }");
    }

    // ── Stream request ────────────────────────────────────────────────────────

    private static void AppendStreamHandleMethod(StringBuilder sb, RequestHandlerModel req)
    {
        sb.AppendLine($$$"""
                    public global::System.Collections.Generic.IAsyncEnumerable<{{{req.ResponseType}}}> Handle(
                        {{{req.RequestType}}} request,
                        global::System.Threading.CancellationToken ct)
                    {
            """);

        if (req.ApplicableMiddleware.Count == 0)
        {
            sb.AppendLine("            return _handler.Handle(request, ct);");
        }
        else
        {
            sb.AppendLine($"            global::Blazing.Mediator.StreamRequestHandlerDelegate<{req.ResponseType}> next = () => _handler.Handle(request, ct);");
            AppendInstanceStreamMiddlewareChain(sb, req.ApplicableMiddleware);
            sb.AppendLine("            return next();");
        }

        sb.AppendLine("        }");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Middleware chain emission helpers (instance-field, no per-call DI lookup)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the closure chain for response-returning request middleware.
    /// Uses pre-resolved instance fields (<c>_mw{i}</c>) — no DI lookup per call.
    /// Middleware is applied in reverse sorted order so that the lowest-<c>Order</c>
    /// middleware ends up outermost (executes first).
    /// Each lambda records itself via <c>MiddlewareExecutionContext</c> when
    /// <c>MiddlewareCaptureMode.Executed</c> is active (null-conditional, so there is
    /// zero overhead in other modes).
    /// </summary>
    private static void AppendInstanceRequestMiddlewareChain(
        StringBuilder sb,
        List<MiddlewareModel> middleware)
    {
        for (int i = middleware.Count - 1; i >= 0; i--)
        {
            var mw       = middleware[i];
            string prevVar  = $"prev{i}";
            string mwType   = GetDiTypeName(mw);

            sb.AppendLine($"            var {prevVar} = next;");

            if (mw.IsConditional)
            {
                sb.AppendLine($$$"""
                            next = () =>
                            {
                                if (!_mw{{{i}}}.ShouldExecute(request))
                                {
                                    global::Blazing.Mediator.Mediator.TrackMiddlewareSkipped(typeof({{{mwType}}}));
                                    return {{{prevVar}}}();
                                }
                                global::Blazing.Mediator.Mediator.TrackMiddlewareExecuted(typeof({{{mwType}}}));
                                return _mw{{{i}}}.HandleAsync(request, {{{prevVar}}}, ct);
                            };
                """);
            }
            else
            {
                sb.AppendLine($$$"""
                            next = () =>
                            {
                                global::Blazing.Mediator.Mediator.TrackMiddlewareExecuted(typeof({{{mwType}}}));
                                return _mw{{{i}}}.HandleAsync(request, {{{prevVar}}}, ct);
                            };
                """);
            }
        }
    }

    /// <summary>
    /// Emits the closure chain for void-command middleware (single type-arg).
    /// Each lambda records itself via the public <c>Mediator.TrackMiddlewareExecuted</c> /
    /// <c>Mediator.TrackMiddlewareSkipped</c> trampoline when
    /// <c>MiddlewareCaptureMode.Executed</c> is active (null-conditional, so there is
    /// zero overhead in other modes).
    /// </summary>
    private static void AppendInstanceVoidMiddlewareChain(
        StringBuilder sb,
        List<MiddlewareModel> middleware)
    {
        for (int i = middleware.Count - 1; i >= 0; i--)
        {
            var mw       = middleware[i];
            string prevVar  = $"prev{i}";
            string mwType   = GetDiTypeName(mw);

            sb.AppendLine($"            var {prevVar} = next;");

            if (mw.IsConditional)
            {
                sb.AppendLine($$$"""
                            next = () =>
                            {
                                if (!_mw{{{i}}}.ShouldExecute(request))
                                {
                                    global::Blazing.Mediator.Mediator.TrackMiddlewareSkipped(typeof({{{mwType}}}));
                                    return {{{prevVar}}}();
                                }
                                global::Blazing.Mediator.Mediator.TrackMiddlewareExecuted(typeof({{{mwType}}}));
                                return _mw{{{i}}}.HandleAsync(request, {{{prevVar}}}, ct);
                            };
                """);
            }
            else
            {
                sb.AppendLine($$$"""
                            next = () =>
                            {
                                global::Blazing.Mediator.Mediator.TrackMiddlewareExecuted(typeof({{{mwType}}}));
                                return _mw{{{i}}}.HandleAsync(request, {{{prevVar}}}, ct);
                            };
                """);
            }
        }
    }

    /// <summary>Emits the closure chain for stream-request middleware.</summary>
    private static void AppendInstanceStreamMiddlewareChain(
        StringBuilder sb,
        List<MiddlewareModel> middleware)
    {
        for (int i = middleware.Count - 1; i >= 0; i--)
        {
            string prevVar = $"prev{i}";
            sb.AppendLine($$$"""
                        var {{{prevVar}}} = next;
                        next = () => _mw{{{i}}}.HandleAsync(request, {{{prevVar}}}, ct);
                """);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Notification handler wrappers
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendNotificationWrapper(
        StringBuilder sb,
        NotificationHandlerModel notif)
    {
        string notifType = notif.NotificationType;
        string safeName  = notif.SafeNotificationName;
        var notifMiddleware = notif.ApplicableNotificationMiddleware;

        // Compute simple type name at codegen time — baked as a string literal in the generated output.
        // Zero runtime overhead, no typeof(T).Name, fully AOT/trim-safe.
        // Uses Substring (not .. range syntax) because this file targets netstandard2.0.
        string simpleNotifName = notifType.Contains('.')
            ? notifType.Substring(notifType.LastIndexOf('.') + 1)
            : notifType.StartsWith("global::", StringComparison.Ordinal)
                ? notifType.Substring("global::".Length)
                : notifType;

        sb.AppendLine($$$"""
                /// <summary>Generated Singleton-cached dispatch wrapper for notification <c>{{{XmlDocTypeName(notifType)}}}</c>.</summary>
                /// <remarks>Pre-resolves all <c>INotificationHandler&lt;T&gt;</c> instances and <c>INotificationPublisher</c> once
                /// at startup via <c>Init(sp)</c>. Subsequent <c>Handle()</c> calls involve zero DI lookups.</remarks>
            """);
        sb.AppendLine($$$"""
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class NotificationHandlerWrapper_{{{safeName}}}
                {
            """);

        // ── Cached fields ─────────────────────────────────────────────────────
        sb.AppendLine($$$"""
                    private global::Blazing.Mediator.INotificationHandler<{{{notifType}}}>[] _handlers = null!;
                    private global::Blazing.Mediator.INotificationPublisher _publisher = null!;
            """);
        // Optional statistics — resolved via GetService (null-safe when stats not configured). AOT-safe: typed GetService, no reflection.
        sb.AppendLine("        private global::Blazing.Mediator.Statistics.MediatorStatistics? _statistics;");
        for (int i = 0; i < notifMiddleware.Count; i++)
            sb.AppendLine($"        private {notifMiddleware[i].MiddlewareType} _nmw{i} = null!;");
        sb.AppendLine();

        // ── Init — called once at startup ─────────────────────────────────────
        sb.AppendLine($$$"""
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public NotificationHandlerWrapper_{{{safeName}}} Init(global::System.IServiceProvider sp)
                    {
                        _handlers = new global::Blazing.Mediator.INotificationHandler<{{{notifType}}}>[]                        {
            """);
        foreach (var handlerType in notif.HandlerTypes)
            sb.AppendLine($"                (global::Blazing.Mediator.INotificationHandler<{notifType}>)sp.GetRequiredService<{handlerType}>(),");
        sb.AppendLine("""
                        };
                        _publisher = sp.GetRequiredService<global::Blazing.Mediator.INotificationPublisher>();
                        _statistics = sp.GetService<global::Blazing.Mediator.Statistics.MediatorStatistics>();
            """);
        for (int i = 0; i < notifMiddleware.Count; i++)
            sb.AppendLine($"            _nmw{i} = sp.GetRequiredService<{notifMiddleware[i].MiddlewareType}>();");
        sb.AppendLine("""
                        return this;
                    }

            """);

        // ── Handle — fast path ────────────────────────────────────────────────
        // [AggressiveInlining] stays effective: this method stays a sync ValueTask return in all cases.
        // When _statistics is null (stats not configured) the branch is a single null-check on a
        // Singleton-cached field — effectively free. No async state machine is ever allocated here.
        sb.AppendLine($$$"""
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public global::System.Threading.Tasks.ValueTask Handle(
                        {{{notifType}}} notification,
                        global::System.Threading.CancellationToken ct)
                    {
                        if (_statistics == null)
            """);

        if (notifMiddleware.Count == 0)
        {
            // Zero middleware — single-line return, zero allocations.
            sb.AppendLine($$$"""
                            return _publisher.Publish(
                                new global::Blazing.Mediator.NotificationHandlers<{{{notifType}}}>(_handlers),
                                notification,
                                ct);
                """);
        }
        else
        {
            // With middleware — build chain inline, still plain ValueTask return.
            sb.AppendLine($$$"""
                            {
                                global::Blazing.Mediator.NotificationDelegate<{{{notifType}}}> next =
                                    (n, token) => _publisher.Publish(new global::Blazing.Mediator.NotificationHandlers<{{{notifType}}}>(_handlers), n, token);
                """);
            for (int i = notifMiddleware.Count - 1; i >= 0; i--)
            {
                string prevVar = $"nprev{i}";
                sb.AppendLine($$$"""
                                var {{{prevVar}}} = next;
                                next = (n, token) => _nmw{{{i}}}.InvokeAsync(n, {{{prevVar}}}, token);
                    """);
            }
            sb.AppendLine("""
                                return next(notification, ct);
                            }
                """);
        }

        sb.AppendLine("""
                        return HandleTracked(notification, ct);
                    }

            """);

        // ── HandleTracked — stats path ────────────────────────────────────────
        // async ValueTask: state machine only materialises when _statistics != null (user opted into stats).
        // RecordExecutionTime / RecordExecutionPattern both have internal EnablePerformanceCounters /
        // EnableDetailedAnalysis guards — safe to call unconditionally.
        // All operation-name strings are baked string literals (computed above at codegen time):
        //   no typeof(T).Name, no reflection anywhere in the generated output — fully AOT/trim-safe.
        sb.AppendLine($$$"""
                    private async global::System.Threading.Tasks.ValueTask HandleTracked(
                        {{{notifType}}} notification,
                        global::System.Threading.CancellationToken ct)
                    {
                        _statistics!.IncrementNotification("{{{simpleNotifName}}}");
                        var _sw = global::System.Diagnostics.Stopwatch.StartNew();
                        bool _success = true;
                        try
                        {
            """);

        if (notifMiddleware.Count == 0)
        {
            sb.AppendLine($$$"""
                            await _publisher.Publish(
                                new global::Blazing.Mediator.NotificationHandlers<{{{notifType}}}>(_handlers),
                                notification,
                                ct).ConfigureAwait(false);
                """);
        }
        else
        {
            sb.AppendLine($$$"""
                                global::Blazing.Mediator.NotificationDelegate<{{{notifType}}}> next =
                                    (n, token) => _publisher.Publish(new global::Blazing.Mediator.NotificationHandlers<{{{notifType}}}>(_handlers), n, token);
                """);
            for (int i = notifMiddleware.Count - 1; i >= 0; i--)
            {
                string prevVar = $"tnprev{i}";
                sb.AppendLine($$$"""
                                var {{{prevVar}}} = next;
                                next = (n, token) => _nmw{{{i}}}.InvokeAsync(n, {{{prevVar}}}, token);
                    """);
            }
            sb.AppendLine("                await next(notification, ct).ConfigureAwait(false);");
        }

        sb.AppendLine($$$"""
                        }
                        catch
                        {
                            _success = false;
                            throw;
                        }
                        finally
                        {
                            _sw.Stop();
                            _statistics!.RecordExecutionTime("Notification:{{{simpleNotifName}}}", _sw.ElapsedMilliseconds, _success);
                            _statistics!.RecordExecutionPattern("Notification:{{{simpleNotifName}}}", global::System.DateTime.UtcNow);
                        }
                    }
                }
            """);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ─────────────────────────────────────────────────────────────────────────
    // Container probe marker types — for Unsafe.As array-backed IEnumerable detection
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits two sealed marker classes (<c>ContainerProbe0</c>, <c>ContainerProbe1</c>)
    /// registered in DI at startup. Querying <c>GetServices&lt;ContainerProbe0&gt;()</c>
    /// after two registrations lets <see cref="AppendContainerMetadata"/> detect whether
    /// the backing store is a real <c>T[]</c>, enabling <c>Unsafe.As&lt;T[]&gt;</c> casts
    /// instead of <c>.ToArray()</c> in hot notification-dispatch paths.
    /// </summary>
    private static void AppendContainerProbes(StringBuilder sb)
    {
        sb.AppendLine("""
                /// <summary>Marker type registered twice to probe the DI container's backing-store type.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class ContainerProbe0 { }

                /// <summary>Secondary marker — not queried directly; ensures two registrations exist for ContainerProbe0.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class ContainerProbe1 { }
            """);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ThrowHelper — [DoesNotReturn] methods for generated dispatch error paths
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the <c>ThrowHelper</c> static class into <c>Mediator.g.cs</c>.
    /// Each method is annotated <c>[DoesNotReturn]</c> so the JIT can eliminate
    /// the normal-return prolog from hot dispatch switch arms that reference them.
    /// </summary>
    private static void AppendThrowHelper(StringBuilder sb)
    {
        sb.AppendLine("""
                /// <summary>Generated dispatch throw-helper — all methods annotated <c>[DoesNotReturn]</c> for JIT hot-path optimisation.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal static class ThrowHelper
                {
                    // ── Void commands ──────────────────────────────────────────────────────
                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask ThrowNoVoidCommandsDiscovered()
                        => throw new global::System.NotImplementedException(
                            "No void command handlers discovered during compilation. Falling back to reflection.");

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask ThrowUnhandledVoidRequest(
                        global::Blazing.Mediator.IRequest request)
                        => throw new global::System.NotImplementedException(
                            $"No void command handler registered for request type '{request.GetType().FullName}'. " +
                            "Ensure the handler implements IRequestHandler<TRequest> and was discovered by Blazing.Mediator.SourceGenerators.");

                    // ── Typed-response requests ────────────────────────────────────────────
                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowNoTypedRequestsDiscovered<TResponse>()
                        => throw new global::System.NotImplementedException(
                            "No request-with-response handlers discovered during compilation. Falling back to reflection.");

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowUnhandledTypedRequest<TResponse>(
                        global::Blazing.Mediator.IRequest<TResponse> request)
                        => throw new global::System.NotImplementedException(
                            $"No handler registered for request type '{request.GetType().FullName}'. " +
                            "Ensure the handler implements IRequestHandler<TRequest,TResponse> and was discovered by Blazing.Mediator.SourceGenerators.");

                    // ── Streaming requests ─────────────────────────────────────────────────
                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> ThrowNoStreamHandlersDiscovered<TResponse>()
                        => throw new global::System.NotImplementedException(
                            "No stream handlers discovered during compilation. Falling back to reflection.");

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> ThrowUnhandledStreamRequest<TResponse>(
                        global::Blazing.Mediator.IStreamRequest<TResponse> request)
                        => throw new global::System.NotImplementedException(
                            $"No stream handler registered for request type '{request.GetType().FullName}'. " +
                            "Ensure the handler implements IStreamRequestHandler<TRequest,TResponse> and was discovered by Blazing.Mediator.SourceGenerators.");

                    // ── Notifications ──────────────────────────────────────────────────────
                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask ThrowNotificationFallback()
                        => throw new global::System.NotImplementedException(
                            "Source-generated notification dispatch is deferred. Falling back to reflection.");

                    // ── Multiple handlers (ambiguous) ───────────────────────────────────────
                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask ThrowMultipleHandlersVoidRequest(
                        global::Blazing.Mediator.IRequest request)
                        => throw new global::System.InvalidOperationException(
                            $"Multiple handlers found for '{request.GetType().Name}'. Only one handler per request type is allowed.");

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowMultipleHandlersTypedRequest<TResponse>(
                        global::Blazing.Mediator.IRequest<TResponse> request)
                        => throw new global::System.InvalidOperationException(
                            $"Multiple handlers found for '{request.GetType().Name}'. Only one handler per request type is allowed.");

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> ThrowMultipleHandlersStreamRequest<TResponse>(
                        global::Blazing.Mediator.IStreamRequest<TResponse> request)
                        => throw new global::System.InvalidOperationException(
                            $"Multiple handlers found for '{request.GetType().Name}'. Only one handler per request type is allowed.");
                } // ThrowHelper
            """);
    }

    // ContainerMetadata — Scoped holding all pre-resolved wrapper instances (one per request scope)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the <c>ContainerMetadata</c> sealed class.
    /// Registered as Scoped in DI; constructor resolves all <c>RequestHandlerWrapper_*</c>
    /// instances once per scope via <c>IServiceProvider</c>, enabling zero-DI-lookup dispatch
    /// while supporting handlers that depend on scoped services (DbContext, per-request services).
    /// </summary>
    private static void AppendContainerMetadata(StringBuilder sb, CompilationModel model)
    {
        sb.AppendLine("""
                /// <summary>Generated per-scope cache holding all pre-initialised request handler wrappers for the current DI scope.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class ContainerMetadata : global::Blazing.Mediator.MediatorDispatcherBase
                {
                    /// <summary>True when the DI container backs <c>GetServices&lt;T&gt;()</c> with a real <c>T[]</c>.</summary>
                    /// <remarks>Used to enable zero-copy <c>Unsafe.As&lt;T[]&gt;</c> casts in notification dispatch.</remarks>
                    public readonly bool ServicesUnderlyingTypeIsArray;

            """);

        foreach (var req in model.Requests)
        {
            // Ambiguous requests have no wrapper class — skip field declaration.
            if (!req.IsAmbiguous)
                sb.AppendLine($"        public readonly RequestHandlerWrapper_{req.SafeName} {req.SafeName};");
        }

        foreach (var notif in model.Notifications)
        {
            sb.AppendLine($"        public readonly NotificationHandlerWrapper_{notif.SafeNotificationName} {notif.SafeNotificationName};");
        }

        sb.AppendLine();
        sb.AppendLine("""
                    public ContainerMetadata(global::System.IServiceProvider sp)
                    {
                        ServicesUnderlyingTypeIsArray =
                            sp.GetServices<ContainerProbe0>() is ContainerProbe0[];
            """);

        foreach (var req in model.Requests)
        {
            // Ambiguous requests have no wrapper class — skip initialisation.
            if (!req.IsAmbiguous)
                sb.AppendLine($"            {req.SafeName} = new RequestHandlerWrapper_{req.SafeName}().Init(sp);");
        }

        foreach (var notif in model.Notifications)
        {
            sb.AppendLine($"            {notif.SafeNotificationName} = new NotificationHandlerWrapper_{notif.SafeNotificationName}().Init(sp);");
        }

        sb.AppendLine("""
                    }

                    // ── MediatorDispatcherBase overrides ─────────────────────────────────
                    /// <inheritdoc/>
                    public override global::System.Threading.Tasks.ValueTask SendAsync(
                        global::Blazing.Mediator.IRequest request,
                        global::System.Threading.CancellationToken cancellationToken)
                        => RequestDispatcher.Send(request, this, cancellationToken);

                    /// <inheritdoc/>
                    public override global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
                        global::Blazing.Mediator.IRequest<TResponse> request,
                        global::System.Threading.CancellationToken cancellationToken)
                        => RequestDispatcher.Send(request, this, cancellationToken);

                    /// <inheritdoc/>
                    public override global::System.Collections.Generic.IAsyncEnumerable<TResponse> SendStreamAsync<TResponse>(
                        global::Blazing.Mediator.IStreamRequest<TResponse> request,
                        global::System.Threading.CancellationToken cancellationToken)
                        => RequestDispatcher.SendStream(request, this, cancellationToken);

                    /// <inheritdoc/>
                    public override global::System.Threading.Tasks.ValueTask PublishAsync<TNotification>(
                        TNotification notification,
                        global::System.Threading.CancellationToken cancellationToken)
                        => NotificationDispatcher.Publish(notification, this, cancellationToken);

                    /// <inheritdoc/>
                    /// <remarks>
                    /// Each <c>typeof(TNotification) == typeof(...)</c> comparison is constant-folded by the
                    /// JIT when <typeparamref name="TNotification"/> is statically known at the call site,
                    /// turning this into a compile-time constant <see langword="true"/> or <see langword="false"/>.
                    /// </remarks>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public override bool IsNotificationHandled<TNotification>()
            """);

        if (model.Notifications.Count == 0)
        {
            sb.AppendLine("            => false;");
        }
        else if (model.Notifications.Count == 1)
        {
            sb.AppendLine($"            => typeof(TNotification) == typeof({model.Notifications[0].NotificationType});");
        }
        else
        {
            sb.AppendLine("""
                        {
            """);
            sb.Append("            return");
            for (int i = 0; i < model.Notifications.Count; i++)
            {
                var notif = model.Notifications[i];
                bool isLast = i == model.Notifications.Count - 1;
                if (i == 0)
                    sb.Append($" typeof(TNotification) == typeof({notif.NotificationType})");
                else
                    sb.Append($"\n                || typeof(TNotification) == typeof({notif.NotificationType})");
                if (isLast)
                    sb.AppendLine(";");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("    } // ContainerMetadata");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // RequestDispatcher — matches the contract expected by Mediator.Send.cs
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the <c>RequestDispatcher</c> static class with:
    /// <list type="bullet">
    ///   <item><c>Send(IRequest, ContainerMetadata, CancellationToken)</c> — void commands</item>
    ///   <item><c>Send&lt;TResponse&gt;(IRequest&lt;TResponse&gt;, ...)</c> — queries / response commands</item>
    ///   <item><c>SendStream&lt;TResponse&gt;(IStreamRequest&lt;TResponse&gt;, ...)</c> — streaming</item>
    ///   <item><c>GetHandlerInterfaceType(Type, Type?)</c> — AOT-safe handler type lookup</item>
    /// </list>
    /// </summary>
    private static void AppendRequestDispatcher(StringBuilder sb, CompilationModel model)
    {
        var voidRequests     = model.Requests.Where(r => r.IsVoid  && !r.IsStream).ToList();
        var typedRequests    = model.Requests.Where(r => !r.IsVoid && !r.IsStream).ToList();
        var streamRequests   = model.Requests.Where(r => r.IsStream).ToList();

        const string cm = "global::Blazing.Mediator.Generated.ContainerMetadata";
        const string ct  = "global::System.Threading.CancellationToken";

        sb.AppendLine("""
                /// <summary>
                /// Generated zero-reflection request dispatcher.
                /// Called by <c>Mediator.Send.cs</c> and <c>Mediator.SendStream.cs</c> via <see cref="global::Blazing.Mediator.MediatorDispatcherBase"/> virtual dispatch.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal static partial class RequestDispatcher
                {
            """);

        // ── Void-command Send ──────────────────────────────────────────────────
        sb.AppendLine($$$"""
                    /// <summary>Dispatches a void command via a pre-resolved wrapper. Throws <see cref="global::System.NotImplementedException"/> for unknown types, triggering the reflection fallback.</summary>
                    public static global::System.Threading.Tasks.ValueTask Send(
                        global::Blazing.Mediator.IRequest request,
                        {{{cm}}} containerMetadata,
                        {{{ct}}} cancellationToken)
                    {
            """);

        if (voidRequests.Count == 0)
        {
            sb.AppendLine("            return ThrowHelper.ThrowNoVoidCommandsDiscovered();");
        }
        else
        {
            sb.AppendLine("""
                            return request switch
                            {
                """);
            foreach (var req in voidRequests)
            {
                if (req.IsAmbiguous)
                    sb.AppendLine($"                {req.RequestType} r => ThrowHelper.ThrowMultipleHandlersVoidRequest(r),");
                else
                    sb.AppendLine($"                {req.RequestType} r => containerMetadata.{req.SafeName}.Handle(r, cancellationToken),");
            }
            sb.AppendLine("""
                                _ => ThrowHelper.ThrowUnhandledVoidRequest(request)
                            };
                """);
        }
        sb.AppendLine("""
                }

            """);

        // ── Generic response Send ─────────────────────────────────────────
        sb.AppendLine($$$"""
                    /// <summary>Dispatches a request-with-response via a pre-resolved wrapper. Returns a faulted <see cref="global::System.Threading.Tasks.ValueTask{TResponse}"/> for unknown types, triggering the reflection fallback.</summary>
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public static global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
                        global::Blazing.Mediator.IRequest<TResponse> request,
                        {{{cm}}} containerMetadata,
                        {{{ct}}} cancellationToken)
                    {
            """);

        if (typedRequests.Count == 0)
        {
            sb.AppendLine("            return ThrowHelper.ThrowNoTypedRequestsDiscovered<TResponse>();");
        }
        else
        {
            sb.AppendLine("""
                            return request switch
                            {
                """);
            foreach (var req in typedRequests)
            {
                if (req.IsAmbiguous)
                {
                    sb.AppendLine($"                {req.RequestType} r => ThrowHelper.ThrowMultipleHandlersTypedRequest<TResponse>((global::Blazing.Mediator.IRequest<TResponse>)(object)r),");
                }
                else
                {
                    // Unsafe.As reinterpretation — zero boxing, zero allocations.
                    sb.AppendLine($$$"""
                                {{{req.RequestType}}} r =>
                                    global::System.Runtime.CompilerServices.Unsafe.As<
                                        global::System.Threading.Tasks.ValueTask<{{{req.ResponseType}}}>,
                                        global::System.Threading.Tasks.ValueTask<TResponse>>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(
                                            containerMetadata.{{{req.SafeName}}}.Handle(r, cancellationToken))),
                    """);
                }
            }
            sb.AppendLine("""
                                _ => ThrowHelper.ThrowUnhandledTypedRequest<TResponse>(request)
                            };
                """);
        }
        sb.AppendLine("""
                }

            """);

        // ── SendStream ─────────────────────────────────────────────────────────────────────
        sb.AppendLine($$$"""
                    /// <summary>Dispatches a stream request via a pre-resolved wrapper. Throws <see cref="global::System.NotImplementedException"/> for unknown types, triggering the reflection fallback.</summary>
                    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> SendStream<TResponse>(
                        global::Blazing.Mediator.IStreamRequest<TResponse> request,
                        {{{cm}}} containerMetadata,
                        {{{ct}}} cancellationToken)
                    {
            """);

        if (streamRequests.Count == 0)
        {
            sb.AppendLine("            return ThrowHelper.ThrowNoStreamHandlersDiscovered<TResponse>();");
        }
        else
        {
            sb.AppendLine("""
                            return request switch
                            {
                """);
            foreach (var req in streamRequests)
            {
                if (req.IsAmbiguous)
                {
                    sb.AppendLine($"                {req.RequestType} r => ThrowHelper.ThrowMultipleHandlersStreamRequest<TResponse>((global::Blazing.Mediator.IStreamRequest<TResponse>)(object)r),");
                }
                else
                {
                    // Use Unsafe.As to reinterpret IAsyncEnumerable<ConcreteType> as IAsyncEnumerable<TResponse>
                    // without an (object) cast / runtime type check — identical to martinothamar's approach.
                    sb.AppendLine($$$"""
                                {{{req.RequestType}}} r =>
                                    global::System.Runtime.CompilerServices.Unsafe.As<
                                        global::System.Collections.Generic.IAsyncEnumerable<{{{req.ResponseType}}}>,
                                        global::System.Collections.Generic.IAsyncEnumerable<TResponse>>(
                                        ref global::System.Runtime.CompilerServices.Unsafe.AsRef(
                                            containerMetadata.{{{req.SafeName}}}.Handle(r, cancellationToken))),
                    """);
                }
            }
            sb.AppendLine("""
                                _ => ThrowHelper.ThrowUnhandledStreamRequest<TResponse>(request)
                            };
                """);
        }
        sb.AppendLine("""
                }

            """);

        // ── GetHandlerInterfaceType — for AOT/SendStream reflection fallback ─
        sb.AppendLine("""
                    /// <summary>Returns the strongly-typed handler interface <c>typeof(IRequestHandler&lt;TReq,TResp&gt;)</c> without <c>MakeGenericType</c>.</summary>
                    public static global::System.Type? GetHandlerInterfaceType(
                        global::System.Type requestType,
                        global::System.Type? responseType = null)
                    {
            """);

        foreach (var req in model.Requests.Where(r => !r.IsStream))
        {
            if (req.IsVoid)
            {
                sb.AppendLine($$$"""
                            if (requestType == typeof({{{req.RequestType}}}))
                                return typeof(global::Blazing.Mediator.IRequestHandler<{{{req.RequestType}}}>);
                    """);
            }
            else
            {
                sb.AppendLine($$$"""
                            if (requestType == typeof({{{req.RequestType}}}) && responseType == typeof({{{req.ResponseType}}}))
                                return typeof(global::Blazing.Mediator.IRequestHandler<{{{req.RequestType}}}, {{{req.ResponseType}}}>);
                    """);
            }
        }
        foreach (var req in streamRequests)
        {
            sb.AppendLine($$$"""
                        if (requestType == typeof({{{req.RequestType}}}) && responseType == typeof({{{req.ResponseType}}}))
                            return typeof(global::Blazing.Mediator.IStreamRequestHandler<{{{req.RequestType}}}, {{{req.ResponseType}}}>);
                """);
        }

        sb.AppendLine("""
                        return null;
                    }
            """);

        sb.AppendLine("    }"); // RequestDispatcher
    }

    // ─────────────────────────────────────────────────────────────────────────
    // NotificationDispatcher — matches the contract expected by Mediator.Notification.cs
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the <c>NotificationDispatcher</c> static class.
    /// Phase 4: dispatches via a compile-time type switch to pre-cached <c>NotificationHandlerWrapper_*</c>
    /// instances held by <see cref="AppendContainerMetadata"/>. Unknown notification types fall through to
    /// <c>ThrowNotificationFallback()</c>, which causes the runtime to fall back to
    /// <c>PublishReflection</c> (handles manual <c>INotificationSubscriber&lt;T&gt;</c> and out-of-assembly types).
    /// </summary>
    private static void AppendNotificationDispatcher(StringBuilder sb, CompilationModel model)
    {
        const string cm = "global::Blazing.Mediator.Generated.ContainerMetadata";
        const string ct = "global::System.Threading.CancellationToken";

        sb.AppendLine($$$"""
                /// <summary>
                /// Generated zero-reflection notification dispatcher.
                /// Dispatches known notification types to pre-cached <c>NotificationHandlerWrapper_*</c> instances.
                /// Throws <see cref="global::System.NotImplementedException"/> for unknown types so the
                /// runtime <c>PublishReflection</c> fallback can handle manual subscribers.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal static class NotificationDispatcher
                {
                    /// <summary>Dispatches a notification via pre-resolved handler wrappers.</summary>
                    public static global::System.Threading.Tasks.ValueTask Publish<TNotification>(
                        TNotification notification,
                        {{{cm}}} containerMetadata,
                        {{{ct}}} cancellationToken)
                        where TNotification : global::Blazing.Mediator.INotification
                    {
            """);

        if (model.Notifications.Count == 0)
        {
            // No notification handlers discovered — always fall back to reflection (subscribers etc.).
            sb.AppendLine("            return ThrowHelper.ThrowNotificationFallback();");
        }
        else
        {
            sb.AppendLine("""
                            return notification switch
                            {
                """);
            // Concrete (non-interface) types must come before interface types in the switch.
            // If an interface arm appears before a sealed concrete type that implements it,
            // the compiler emits CS8510 (unreachable pattern) for the concrete arm.
            foreach (var notif in model.Notifications.Where(n => !n.IsInterface))
            {
                sb.AppendLine($"                {notif.NotificationType} n => containerMetadata.{notif.SafeNotificationName}.Handle(n, cancellationToken),");
            }
            foreach (var notif in model.Notifications.Where(n => n.IsInterface))
            {
                sb.AppendLine($"                {notif.NotificationType} n => containerMetadata.{notif.SafeNotificationName}.Handle(n, cancellationToken),");
            }
            // Unknown notification type — triggers PublishReflection fallback in Mediator.Notification.cs.
            sb.AppendLine("""
                                _ => ThrowHelper.ThrowNotificationFallback()
                            };
                """);
        }

        sb.AppendLine("""
                    }
                }
            """); // NotificationDispatcher
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TelemetryTags — matches the contract expected by Mediator.Notification.cs
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits the <c>TelemetryTags</c> static class and <c>NotificationMetadata</c> struct.
    /// Called from both <c>Publish&lt;TNotification&gt;</c> and <c>PublishReflection&lt;TNotification&gt;</c>
    /// under <c>#if USE_SOURCE_GENERATORS</c> for zero-reflection notification type name lookup.
    /// </summary>
    private static void AppendTelemetryTags(StringBuilder sb, CompilationModel model)
    {
        sb.AppendLine("""
                /// <summary>Generated compile-time notification type metadata for zero-reflection telemetry label lookup.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal static class TelemetryTags
                {
                    /// <summary>Returns telemetry metadata for a notification type discovered at compile time.</summary>
                    public static bool TryGetNotificationMetadata(
                        global::System.Type type,
                        out NotificationMetadata metadata)
                    {
            """);

        if (model.Notifications.Count == 0)
        {
            sb.AppendLine("""
                            metadata = default;
                            return false;
                """);
        }
        else
        {
            foreach (var notif in model.Notifications)
            {
                // SimpleName: last segment after last '.' in the FQN, strip generic backtick if any
                string fqn         = notif.NotificationType;       // e.g. global::MyApp.UserCreatedNotification
                string simpleName  = GetSimpleName(fqn);           // e.g. "UserCreatedNotification"
                string sanitized   = SanitizeForOtel(simpleName);  // e.g. "UserCreated_Notification"

                sb.AppendLine($$$"""
                            if (type == typeof({{{fqn}}}))
                            {
                                metadata = new NotificationMetadata("{{{simpleName}}}", "{{{sanitized}}}");
                                return true;
                            }
                """);
            }
            sb.AppendLine("""
                            metadata = default;
                            return false;
                """);
        }

        sb.AppendLine("""
                }

            """);

        // ── TryGetRequestMetadata ─────────────────────────────────────────────
        sb.AppendLine("""
                    /// <summary>Returns telemetry metadata for a request or handler type discovered at compile time.</summary>
                    public static bool TryGetRequestMetadata(
                        global::System.Type type,
                        out RequestMetadata metadata)
                    {
            """);

        // Emit lookup for all request types AND their handler types.
        if (model.Requests.Count == 0)
        {
            sb.AppendLine("""
                            metadata = default;
                            return false;
                """);
        }
        else
        {
            foreach (var req in model.Requests)
            {
                string reqFqn       = req.RequestType;
                string reqSimple    = GetSimpleName(reqFqn);
                string reqSanitized = SanitizeForOtel(reqSimple);

                // For ambiguous requests, emit an entry for each individual handler type.
                var handlers = req.AllHandlerTypes;
                foreach (var handlerFqn in handlers)
                {
                    string handlerSimple    = GetSimpleName(handlerFqn);
                    string handlerSanitized = SanitizeForOtel(handlerSimple);

                    // Match by request type (only emit once, from first handler)
                    if (handlerFqn == handlers[0])
                    {
                        sb.AppendLine($$$"""
                                    if (type == typeof({{{reqFqn}}}))
                                    {
                                        metadata = new RequestMetadata("{{{reqSimple}}}", "{{{reqSanitized}}}", "{{{handlerSimple}}}", "{{{handlerSanitized}}}");
                                        return true;
                                    }
                        """);
                    }

                    // Match by handler type
                    sb.AppendLine($$$"""
                                if (type == typeof({{{handlerFqn}}}))
                                {
                                    metadata = new RequestMetadata("{{{reqSimple}}}", "{{{reqSanitized}}}", "{{{handlerSimple}}}", "{{{handlerSanitized}}}");
                                    return true;
                                }
                    """);
                }
            }
            sb.AppendLine("""
                            metadata = default;
                            return false;
                """);
        }

        sb.AppendLine("""
                    }
                }

            """); // TelemetryTags

        // ── RequestMetadata struct ────────────────────────────────────────────
        sb.AppendLine("""
                /// <summary>Compile-time request telemetry label metadata.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                internal readonly struct RequestMetadata
                {
                    /// <summary>Initialises the metadata record.</summary>
                    public RequestMetadata(string requestName, string sanitizedRequestName, string handlerName, string sanitizedHandlerName)
                    {
                        RequestName = requestName;
                        SanitizedRequestName = sanitizedRequestName;
                        HandlerName = handlerName;
                        SanitizedHandlerName = sanitizedHandlerName;
                    }

                    /// <summary>Simple short request type name, e.g. <c>PingRequest</c>.</summary>
                    public string RequestName { get; }

                    /// <summary>OTel-safe request name with special chars replaced.</summary>
                    public string SanitizedRequestName { get; }

                    /// <summary>Simple short handler type name.</summary>
                    public string HandlerName { get; }

                    /// <summary>OTel-safe handler name with special chars replaced.</summary>
                    public string SanitizedHandlerName { get; }
                } // RequestMetadata

            """);

        // ── NotificationMetadata struct ───────────────────────────────────────
        sb.AppendLine("""
                /// <summary>Compile-time notification telemetry label metadata.</summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                internal readonly struct NotificationMetadata
                {
                    /// <summary>Initialises the metadata record.</summary>
                    public NotificationMetadata(string notificationName, string sanitizedNotificationName)
                    {
                        NotificationName = notificationName;
                        SanitizedNotificationName = sanitizedNotificationName;
                    }

                    /// <summary>Simple short type name, e.g. <c>UserCreatedNotification</c>.</summary>
                    public string NotificationName { get; }

                    /// <summary>OTel-safe name with dots/angle-brackets replaced, e.g. <c>UserCreated_Notification</c>.</summary>
                    public string SanitizedNotificationName { get; }
                } // NotificationMetadata
            """);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // MediatorTypeCatalog — AOT-clean compile-time handler catalog
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendTypeCatalog(StringBuilder sb, CompilationModel model)
    {
        sb.AppendLine("""
                /// <summary>
                /// Compile-time catalog of every handler and notification type discovered by the source generator.
                /// Implements <see cref="global::Blazing.Mediator.Statistics.IMediatorTypeCatalog" /> for fully AOT-clean
                /// analysis via <c>MediatorStatistics.AnalyzeQueries(IMediatorTypeCatalog)</c>.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class MediatorTypeCatalog : global::Blazing.Mediator.Statistics.IMediatorTypeCatalog
                {
                    /// <summary>Singleton instance — all data is compile-time constant, no allocation on first access.</summary>
                    public static readonly MediatorTypeCatalog Instance = new();

            """);

        // ── RequestHandlers ────────────────────────────────────────────────
        sb.AppendLine("""
                public global::System.Collections.Generic.IReadOnlyList<global::Blazing.Mediator.Statistics.HandlerTypeInfo> RequestHandlers { get; } =
                [
            """);
        foreach (var req in model.Requests)
        {
            string requestName = GetSimpleName(req.RequestType);
            string responseArg = req.IsVoid ? "null" : $"typeof({req.ResponseType})";
            string category    = DetermineCqrsCategory(req);
            // For ambiguous requests, emit one catalog entry per handler type.
            foreach (var handlerFqn in req.AllHandlerTypes)
                sb.AppendLine($"            new(\"{requestName}\", typeof({req.RequestType}), {responseArg}, typeof({handlerFqn}), {category}),");
        }
        sb.AppendLine("""
                ];

            """);

        // ── NotificationHandlers ───────────────────────────────────────────
        sb.AppendLine("""
                public global::System.Collections.Generic.IReadOnlyList<global::Blazing.Mediator.Statistics.NotificationTypeInfo> NotificationHandlers { get; } =
                [
            """);
        foreach (var notif in model.Notifications)
        {
            string notificationName = GetSimpleName(notif.NotificationType);
            sb.AppendLine($"            new(\"{notificationName}\", typeof({notif.NotificationType}),");
            sb.Append("                [");
            if (notif.HandlerTypes.Count == 0)
            {
                sb.AppendLine("]),");
            }
            else
            {
                sb.AppendLine();
                foreach (var ht in notif.HandlerTypes)
                {
                    sb.AppendLine($"                    typeof({ht}),");
                }
                sb.AppendLine("                ]),");
            }
        }
        sb.AppendLine("""
                ];

            """);

        // ── RequestMiddleware ──────────────────────────────────────────────
        sb.AppendLine("""
                public global::System.Collections.Generic.IReadOnlyList<global::Blazing.Mediator.Statistics.MiddlewareTypeInfo> RequestMiddleware { get; } =
                [
            """);
        foreach (var mw in model.Middleware.Where(static m => !m.IsNotification))
        {
            string mwName = GetSimpleName(mw.IsOpenGeneric ? mw.OpenGenericBaseType! : mw.MiddlewareType);
            // Open-generic request middleware arity: void-command variant has 1 type arg (<>),
            // regular and stream variants have 2 type args (<,>).
            string mwType = mw.IsOpenGeneric
                ? (mw.IsVoidCommand ? $"typeof({mw.OpenGenericBaseType!}<>)" : $"typeof({mw.OpenGenericBaseType!}<,>)")
                : $"typeof({mw.MiddlewareType})";
            sb.AppendLine($"            new(\"{mwName}\", {mwType}, {mw.Order}, {(mw.IsOpenGeneric ? "true" : "false")}, false),");
        }
        sb.AppendLine("""
                ];

            """);

        // ── NotificationMiddleware ─────────────────────────────────────────
        sb.AppendLine("""
                public global::System.Collections.Generic.IReadOnlyList<global::Blazing.Mediator.Statistics.MiddlewareTypeInfo> NotificationMiddleware { get; } =
                [
            """);
        foreach (var mw in model.Middleware.Where(static m => m.IsNotification))
        {
            string mwName = GetSimpleName(mw.IsOpenGeneric ? mw.OpenGenericBaseType! : mw.MiddlewareType);
            string mwType = mw.IsOpenGeneric
                ? $"typeof({mw.OpenGenericBaseType!}<>)"
                : $"typeof({mw.MiddlewareType})";
            sb.AppendLine($"            new(\"{mwName}\", {mwType}, {mw.Order}, {(mw.IsOpenGeneric ? "true" : "false")}, true),");
        }
        sb.AppendLine("""
                ];
            } // MediatorTypeCatalog
            """);
    }

    /// <summary>
    /// Derives the <c>CqrsCategory</c> for a request handler model using compile-time flags.
    /// </summary>
    private static string DetermineCqrsCategory(RequestHandlerModel req)
    {
        if (req.IsStream) return "global::Blazing.Mediator.Statistics.CqrsCategory.Stream";
        if (req.IsVoid)   return "global::Blazing.Mediator.Statistics.CqrsCategory.Command";
        if (req.IsQuery)  return "global::Blazing.Mediator.Statistics.CqrsCategory.Query";
        return "global::Blazing.Mediator.Statistics.CqrsCategory.Command"; // command with response
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Service registration extension
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendServiceRegistrationExtension(StringBuilder sb, CompilationModel model)
    {
        sb.AppendLine("""
                /// <summary>
                /// Generated extension method that registers all handlers and middleware discovered at compile-time.
                /// Call <c>services.AddMediator()</c> to register all compile-time-discovered handlers and middleware.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class MediatorServiceCollectionExtensions
                {
                    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMediator(
                        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    {
            """);

        // ── Request handlers ──────────────────────────────────────────────────
        if (model.Requests.Count > 0)
        {
            sb.AppendLine("            // Request / command / query / stream handlers");
            var registeredHandlers = new HashSet<string>();
            foreach (var req in model.Requests)
            {
                // For ambiguous requests, register ALL discovered handler types
                // so the error message at runtime can identify which ones conflict.
                if (req.IsAmbiguous)
                {
                    foreach (var ht in req.AllHandlerTypes)
                    {
                        if (registeredHandlers.Add(ht))
                            sb.AppendLine($"            services.AddScoped<{ht}>();");
                    }
                }
                else
                {
                    if (registeredHandlers.Add(req.HandlerType))
                    {
                        sb.AppendLine($"            services.AddScoped<{req.HandlerType}>();");
                        // Dual-register under IRequestHandler<T,R> so DI-based statistics analysis can find handlers.
                        // Streams implement IStreamRequestHandler<T,R> — skip IRequestHandler registration for them.
                        if (!req.IsStream)
                        {
                            if (req.IsVoid)
                                sb.AppendLine($"            services.AddScoped<global::Blazing.Mediator.IRequestHandler<{req.RequestType}>, {req.HandlerType}>();");
                            else
                                sb.AppendLine($"            services.AddScoped<global::Blazing.Mediator.IRequestHandler<{req.RequestType}, {req.ResponseType}>, {req.HandlerType}>();");
                        }
                    }
                }
            }
            sb.AppendLine();
        }

        // ── Notification handlers ─────────────────────────────────────────────
        if (model.Notifications.Count > 0)
        {
            sb.AppendLine("            // Notification handlers");
            var registeredHandlers = new HashSet<string>();
            foreach (var notif in model.Notifications)
            {
                foreach (var handlerType in notif.HandlerTypes)
                {
                    if (registeredHandlers.Add(handlerType))
                    {
                        sb.AppendLine($"            services.AddScoped<{handlerType}>();");
                    }
                    // Always register under INotificationHandler<T> for each notification-handler pair.
                    sb.AppendLine($"            services.AddScoped<global::Blazing.Mediator.INotificationHandler<{notif.NotificationType}>, {handlerType}>();");
                }
            }
            sb.AppendLine();
        }

        // ── Notification middleware ───────────────────────────────────────────
        var notifMw = model.Middleware.Where(static m => m.IsNotification).ToList();
        if (notifMw.Count > 0)
        {
            sb.AppendLine("            // Notification middleware");
            var registered = new HashSet<string>();
            foreach (var mw in notifMw)
            {
                if (mw.IsOpenGeneric)
                {
                    // Open-generic notification middleware (e.g. DomainEventMiddleware<TNotification>)
                    // must be registered as an open-generic type so DI can create closed instances.
                    string openType = $"{mw.OpenGenericBaseType!}<>";
                    if (registered.Add(openType))
                        sb.AppendLine($"            services.AddTransient(typeof({openType}));");
                }
                else
                {
                    if (registered.Add(mw.MiddlewareType))
                        sb.AppendLine($"            services.AddTransient<{mw.MiddlewareType}>();");
                }
            }
            sb.AppendLine();
        }

        // ── Request middleware (closed forms) ─────────────────────────────────
        var requestMwRegistered = new HashSet<string>();

        foreach (var req in model.Requests)
        {
            foreach (var mw in req.ApplicableMiddleware)
            {
                string diType = GetDiTypeName(mw);
                if (requestMwRegistered.Add(diType))
                {
                    if (mw.IsOpenGeneric)
                        sb.AppendLine($$$"""
                                    // Closed form of open-generic middleware for {{{req.RequestType}}}
                                    services.AddTransient<{{{diType}}}>();
                        """);
                    else
                        sb.AppendLine($"            services.AddTransient<{diType}>();");
                }
            }
        }

        // Remaining closed, non-notification, non-registered middleware
        foreach (var mw in model.Middleware.Where(static m => !m.IsNotification && !m.IsOpenGeneric))
        {
            if (requestMwRegistered.Add(mw.MiddlewareType))
                sb.AppendLine($"            services.AddTransient<{mw.MiddlewareType}>();");
        }

        sb.AppendLine("""
                        // Container probe — registered twice so GetServices<ContainerProbe0>() returns ContainerProbe0[]
                        // This populates ServicesUnderlyingTypeIsArray used for zero-copy Unsafe.As<T[]> in hot paths.
                        services.AddTransient<global::Blazing.Mediator.Generated.ContainerProbe0>();
                        services.AddTransient<global::Blazing.Mediator.Generated.ContainerProbe0>();

                        // Type catalog — singleton for AOT-clean analysis (no reflection at runtime)
                        services.AddSingleton<global::Blazing.Mediator.Statistics.IMediatorTypeCatalog>(global::Blazing.Mediator.Generated.MediatorTypeCatalog.Instance);

                        // ContainerMetadata — Scoped so each request scope gets its own handler instances.
                        // Scoped (not Singleton) is required when any handler has scoped dependencies (e.g. DbContext,
                        // IContactService). Mirrors master's AddScoped<IMediator>() pattern. Console apps that resolve
                        // services from host.Services.CreateScope() are unaffected — an explicit scope is already the
                        // ambient scope for those code paths.
                        services.AddScoped<global::Blazing.Mediator.Generated.ContainerMetadata>();
                        // MediatorDispatcherBase — allows the library's Mediator class to find the
                        // generated dispatcher via DI without a compile-time type reference.
                        services.AddScoped<global::Blazing.Mediator.MediatorDispatcherBase>(
                            static sp => sp.GetRequiredService<global::Blazing.Mediator.Generated.ContainerMetadata>());

                        // IMediator — Scoped so each request/scope receives its own Mediator instance backed by
                        // the scope's IServiceProvider. Handlers can then safely consume scoped services
                        // (DbContext, per-request services) without captive-dependency issues.
                        services.AddScoped<global::Blazing.Mediator.IMediator, global::Blazing.Mediator.Mediator>();

                        // Default notification publisher — required by source-generated notification wrappers.
                        // TryAddSingleton ensures a user-provided INotificationPublisher (registered before AddMediator())
                        // is never overwritten by this default.
                        services.TryAddSingleton<global::Blazing.Mediator.INotificationPublisher,
                            global::Blazing.Mediator.Notifications.SequentialNotificationPublisher>();

            """);
        // ── Pipeline inspectors — pre-seeded with compile-time-baked orders ─────
        // Register MiddlewarePipelineBuilder and NotificationPipelineBuilder as singletons that are
        // pre-populated with the exact middleware types and order values determined at compile time
        // by the source generator (read from Roslyn syntax — zero runtime reflection).
        // This makes IMiddlewarePipelineInspector.GetDetailedMiddlewareInfo() fully AOT-safe.
        var pbRequestMw = model.Middleware.Where(static m => !m.IsNotification).ToList();
        var pbNotifMw   = model.Middleware.Where(static m =>  m.IsNotification).ToList();

        sb.AppendLine("""
                        // Pipeline inspectors pre-seeded with compile-time order values — no runtime reflection.
                        var _requestPb = new global::Blazing.Mediator.Pipeline.MiddlewarePipelineBuilder();
            """);
        foreach (var mw in pbRequestMw)
        {
            string mwType = mw.IsOpenGeneric
                ? (mw.IsVoidCommand ? $"typeof({mw.OpenGenericBaseType!}<>)" : $"typeof({mw.OpenGenericBaseType!}<,>)")
                : $"typeof({mw.MiddlewareType})";
            sb.AppendLine($"            _requestPb.AddMiddleware({mwType}, {mw.Order});");
        }
        sb.AppendLine("""
                        services.TryAddSingleton<global::Blazing.Mediator.Pipeline.MiddlewarePipelineBuilder>(_requestPb);
                        services.TryAddSingleton<global::Blazing.Mediator.IMiddlewarePipelineInspector>(
                            static sp => sp.GetRequiredService<global::Blazing.Mediator.Pipeline.MiddlewarePipelineBuilder>());
                        services.TryAddSingleton<global::Blazing.Mediator.Pipeline.IMiddlewarePipelineBuilder>(
                            static sp => sp.GetRequiredService<global::Blazing.Mediator.Pipeline.MiddlewarePipelineBuilder>());
                        var _notifPb = new global::Blazing.Mediator.Pipeline.NotificationPipelineBuilder();
            """);
        foreach (var mw in pbNotifMw)
        {
            string mwType = mw.IsOpenGeneric
                ? $"typeof({mw.OpenGenericBaseType!}<>)"
                : $"typeof({mw.MiddlewareType})";
            sb.AppendLine($"            _notifPb.AddMiddleware({mwType}, {mw.Order});");
        }
        sb.AppendLine("""
                        services.TryAddSingleton<global::Blazing.Mediator.Pipeline.NotificationPipelineBuilder>(_notifPb);
                        services.TryAddSingleton<global::Blazing.Mediator.INotificationMiddlewarePipelineInspector>(
                            static sp => sp.GetRequiredService<global::Blazing.Mediator.Pipeline.NotificationPipelineBuilder>());
                        services.TryAddSingleton<global::Blazing.Mediator.Pipeline.INotificationPipelineBuilder>(
                            static sp => sp.GetRequiredService<global::Blazing.Mediator.Pipeline.NotificationPipelineBuilder>());

                        return services;
                    }

            """);

        // ── Config-aware overload ─────────────────────────────────────────────
        sb.AppendLine("""
                    /// <summary>
                    /// Registers all compile-time-discovered handlers and conditionally registers built-in
                    /// feature middleware (telemetry, logging, statistics) and the appropriate
                    /// <see cref="global::Blazing.Mediator.INotificationPublisher"/> based on
                    /// <paramref name="config"/> and the optional <paramref name="configure"/> delegate.
                    /// </summary>
                    /// <param name="services">The <see cref="global::Microsoft.Extensions.DependencyInjection.IServiceCollection"/> to configure.</param>
                    /// <param name="config">Runtime mediator configuration that drives conditional middleware registration.</param>
                    /// <param name="configure">Optional delegate to customise <see cref="global::Blazing.Mediator.Configuration.MediatorOptions"/>.</param>
                    [global::System.CodeDom.Compiler.GeneratedCode("Blazing.Mediator.SourceGenerators", "2.0.0")]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMediator(
                        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                        global::Blazing.Mediator.Configuration.MediatorConfiguration config,
                        global::System.Action<global::Blazing.Mediator.Configuration.MediatorOptions>? configure = null)
                    {
                        // Register all compile-time-discovered handlers and the type catalog.
                        MediatorServiceCollectionExtensions.AddMediator(services);

                        // Apply MediatorOptions customisations.
                        var mediatorOptions = new global::Blazing.Mediator.Configuration.MediatorOptions();
                        configure?.Invoke(mediatorOptions);

                        // ── Notification publisher ─────────────────────────────────────────────
                        // When telemetry is enabled with per-handler child spans, use the telemetry
                        // publisher variant so that each handler invocation gets its own Activity span.
                        // Otherwise use the plain sequential or concurrent publisher.
                        if (config.TelemetryOptions is not null && config.TelemetryOptions.CreateHandlerChildSpans)
                        {
                            if (mediatorOptions.NotificationPublisher == global::Blazing.Mediator.Configuration.NotificationPublisherType.Concurrent)
                                services.AddSingleton<global::Blazing.Mediator.INotificationPublisher,
                                    global::Blazing.Mediator.Notifications.TelemetryConcurrentPublisher>();
                            else
                                services.AddSingleton<global::Blazing.Mediator.INotificationPublisher,
                                    global::Blazing.Mediator.Notifications.TelemetrySequentialPublisher>();
                        }
                        else if (mediatorOptions.NotificationPublisher == global::Blazing.Mediator.Configuration.NotificationPublisherType.Concurrent)
                        {
                            services.AddSingleton<global::Blazing.Mediator.INotificationPublisher,
                                global::Blazing.Mediator.Notifications.ConcurrentNotificationPublisher>();
                        }
                        else
                        {
                            services.AddSingleton<global::Blazing.Mediator.INotificationPublisher,
                                global::Blazing.Mediator.Notifications.SequentialNotificationPublisher>();
                        }

                        // ── Telemetry middleware ───────────────────────────────────────────────
                        if (config.TelemetryOptions is not null)
                        {
                            // Register TelemetryOptions so TelemetryNotificationMiddleware and telemetry publishers
                            // (TelemetrySequentialPublisher / TelemetryConcurrentPublisher) can resolve it via DI.
                            services.AddSingleton(config.TelemetryOptions!);
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.TelemetryMiddleware<,>));
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.TelemetryMiddleware<>));
                            services.AddSingleton<global::Blazing.Mediator.Middleware.TelemetryNotificationMiddleware>();
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.StreamTelemetryMiddleware<,>));
                        }

                        // ── Logging middleware ─────────────────────────────────────────────────
                        if (config.LoggingOptions is not null)
                        {
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.LoggingMiddleware<,>));
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.LoggingMiddleware<>));
                        }

                        // ── Statistics middleware ──────────────────────────────────────────────
                        if (config.StatisticsOptions is not null)
                        {
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.StatisticsMiddleware<,>));
                            services.AddTransient(
                                typeof(global::Blazing.Mediator.Middleware.StatisticsMiddleware<>));
                            // Register StatisticsOptions so StatisticsMiddleware can resolve it via DI.
                            services.AddSingleton(config.StatisticsOptions!);
                            // Register MediatorStatistics; fall back to ConsoleStatisticsRenderer
                            // if the user has not registered their own IStatisticsRenderer.
                            services.AddSingleton(sp =>
                                new global::Blazing.Mediator.Statistics.MediatorStatistics(
                                    sp.GetService<global::Blazing.Mediator.Statistics.IStatisticsRenderer>()
                                        ?? new global::Blazing.Mediator.Statistics.ConsoleStatisticsRenderer(),
                                    config.StatisticsOptions));
                            // Register SubscriberTracker so Mediator.Subscribe() can record subscriptions for analysis.
                            // Gated on StatisticsOptions — zero cost (tracker never allocated) when stats are disabled.
                            services.AddSingleton<global::Blazing.Mediator.ISubscriberTracker, global::Blazing.Mediator.Statistics.SubscriberTracker>();
                        }

                        return services;
                    }
                } // MediatorServiceCollectionExtensions
            """);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helper utilities
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the <c>global::</c>-prefixed type name suitable as a DI GetRequiredService type argument.
    /// <list type="bullet">
    ///   <item>Closed/concrete middleware: <c>global::MyApp.SomeMiddleware</c></item>
    ///   <item>
    ///     Open-generic with one response type arg:
    ///     <c>global::MyApp.LoggingMiddleware&lt;global::MyApp.PingRequest, global::MyApp.PingResponse&gt;</c>
    ///   </item>
    ///   <item>
    ///     Open-generic void-command (single type arg):
    ///     <c>global::MyApp.AuditMiddleware&lt;global::MyApp.CreateOrderCommand&gt;</c>
    ///   </item>
    /// </list>
    /// </summary>
    private static string GetDiTypeName(MiddlewareModel mw)
    {
        // All type names in the model already carry "global::" from SymbolDisplayFormat.FullyQualifiedFormat.
        if (!mw.IsOpenGeneric)
            return mw.MiddlewareType;

        // Open-generic: build closed form from the base name + concrete type arguments.
        // e.g. global::MyApp.LoggingMiddleware<global::MyApp.PingRequest, global::MyApp.PingResponse>
        string baseName = mw.OpenGenericBaseType!;  // already "global::Ns.ClassName"
        string reqArg   = mw.ClosedRequestType!;    // already "global::Ns.RequestType"

        if (mw.ClosedResponseType is null)
        {
            // Single type-arg: void command or single-arg middleware
            return $"{baseName}<{reqArg}>";
        }

        string respArg = mw.ClosedResponseType;     // already "global::Ns.ResponseType"
        return $"{baseName}<{reqArg}, {respArg}>";
    }

    /// <summary>
    /// Extracts the simple class name from a fully-qualified <c>global::Ns.ClassName</c> string.
    /// Handles generic backtick suffixes, e.g. <c>global::Ns.MyClass`1</c> → <c>MyClass</c>.
    /// </summary>
    private static string GetSimpleName(string fqn)
    {
        // Strip "global::" prefix and any namespace segments, then strip generic suffix
        string noPrefix = fqn.StartsWith("global::") ? fqn.Substring(8) : fqn;
        int dotIdx = noPrefix.LastIndexOf('.');
        string simple = dotIdx >= 0 ? noPrefix.Substring(dotIdx + 1) : noPrefix;
        int backtick = simple.IndexOf('`');
        return backtick >= 0 ? simple.Substring(0, backtick) : simple;
    }

    /// <summary>
    /// Replaces dots, generic brackets, angle brackets, and other non-alphanumeric chars with underscores
    /// to produce an OTel-safe activity name component.
    /// </summary>
    private static string SanitizeForOtel(string name)
    {
        var result = new System.Text.StringBuilder(name.Length);
        foreach (char c in name)
        {
            result.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return result.ToString();
    }

    /// <summary>
    /// Sanitizes a fully-qualified type name for safe use inside an XML documentation comment.
    /// Removes the <c>global::</c> prefix and replaces <c>&lt;</c>/<c>&gt;</c> with <c>{</c>/<c>}</c>
    /// so the result is valid XML and readable.
    /// </summary>
    private static string XmlDocTypeName(string typeName)
        => typeName.Replace("global::", "").Replace('<', '{').Replace('>', '}');
}
